version: '3'

services:
  app:
    build:
      context: .
      args:
        - PUBLIC_CLIENT_ID=${PUBLIC_CLIENT_ID}
        - DUMMY_API_KEY=${DUMMY_API_KEY}
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PUBLIC_CLIENT_ID=${PUBLIC_CLIENT_ID}
      - DUMMY_API_KEY=${DUMMY_API_KEY}
